//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.19 at 01:18:14 AM ICT
//


package net.sf.gee.hbase.config.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for mapping complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.sourceforge.net/p/g-ee/ghbase_mapping}host_info"/>
 *         &lt;element name="properties" type="{http://www.sourceforge.net/p/g-ee/ghbase_mapping}properties" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "mapping", namespace = "http://www.sourceforge.net/p/g-ee/ghbase_mapping")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {"host", "properties", "clazz"})
public class Mapping {

  @XmlElement(namespace = "http://www.sourceforge.net/p/g-ee/ghbase_mapping", required = true)
  protected HostInfo host;
  @XmlElement(namespace = "http://www.sourceforge.net/p/g-ee/ghbase_mapping")
  protected Properties properties;
  @XmlElement(name = "class", namespace = "http://www.sourceforge.net/p/g-ee/ghbase_mapping")
  protected List<String> clazz;

  /**
   * Gets the value of the host property.
   * 
   * @return possible object is {@link HostInfo }
   * 
   */
  public HostInfo getHost() {
    return host;
  }

  /**
   * Sets the value of the host property.
   * 
   * @param value allowed object is {@link HostInfo }
   * 
   */
  public void setHost(HostInfo value) {
    this.host = value;
  }

  /**
   * Gets the value of the properties property.
   * 
   * @return possible object is {@link Properties }
   * 
   */
  public Properties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the properties property.
   * 
   * @param value allowed object is {@link Properties }
   * 
   */
  public void setProperties(Properties value) {
    this.properties = value;
  }

  /**
   * Gets the value of the clazz property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the clazz property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getClazz().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link String }
   * 
   * 
   */
  public List<String> getClazz() {
    if (clazz == null) {
      clazz = new ArrayList<String>();
    }
    return this.clazz;
  }

}
